# Generated by Django 4.2.23 on 2026-06-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ultrasound', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUltrasoundDocument',
        ),
    ]
