# Generated by Django 5.2.15 on 2026-07-03 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uhid', '0002_historicalpatient'),
        ('ultrasound', '0003_ultrasoundexpense_age_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ultrasoundinvestigation',
            options={'ordering': ['-test_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='ultrasoundinvestigation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultrasound_bills', to='uhid.patient'),
        ),
    ]
