# Generated by Django 5.2.17 on 2026-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_notification_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant'), ('Maintenance', 'Maintenance')], db_index=True, default='Vacant', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalbed',
            name='status',
            field=models.CharField(choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant'), ('Maintenance', 'Maintenance')], db_index=True, default='Vacant', max_length=20),
        ),
    ]
