# Generated by Django 6.0.2 on 2026-06-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uhid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipd_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('guardian', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(default='General', max_length=50)),
                ('consultant', models.CharField(blank=True, max_length=200)),
                ('kyc_type', models.CharField(blank=True, max_length=50)),
                ('kyc_no', models.CharField(blank=True, max_length=50)),
                ('room_category', models.CharField(blank=True, max_length=100)),
                ('room_no', models.CharField(blank=True, max_length=20)),
                ('diagnosis', models.TextField(blank=True)),
                ('tpa', models.CharField(blank=True, max_length=200)),
                ('policy_no', models.CharField(blank=True, max_length=100)),
                ('insurance_co', models.CharField(blank=True, max_length=200)),
                ('referral', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Admitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipd_admissions', to='uhid.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='ipd.ipdadmission')),
            ],
        ),
        migrations.CreateModel(
            name='IPDMedicineLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_lines', to='ipd.ipdadmission')),
            ],
        ),
        migrations.CreateModel(
            name='IPDPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(default='Cash', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ipd.ipdadmission')),
            ],
        ),
    ]
