# Generated by Django 4.2.23 on 2026-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0004_historicalipdpayment_upi_id_ipdpayment_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalipdadmission',
            name='bed_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='bed_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
