# Generated by Django 5.2.16 on 2026-07-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0005_historicalipdadmission_bed_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalipdpayment',
            name='is_opd_carry_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipdpayment',
            name='is_opd_carry_forward',
            field=models.BooleanField(default=False),
        ),
    ]
