# Generated by Django 5.2.16 on 2026-07-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0006_add_is_opd_carry_forward_to_ipdpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalipdadmission',
            name='doctor_fees',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Consultant / doctor fees for this admission.', max_digits=10),
        ),
        migrations.AddField(
            model_name='ipdadmission',
            name='doctor_fees',
            field=models.DecimalField(decimal_places=2, default=2000, help_text='Consultant / doctor fees for this admission.', max_digits=10),
        ),
    ]
