# Generated by Kiro on 2026-07-28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0007_add_doctor_fees_to_ipdadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ipd_documents/%Y/%m/')),
                ('name', models.CharField(blank=True, help_text='Optional display label', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ipd.ipdadmission')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
