# Generated by Django 5.2.16 on 2026-07-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0008_ipddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalipdadmission',
            name='doctor_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Consultant / doctor fees for this admission.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='doctor_fees',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Consultant / doctor fees for this admission.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='ipddocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
