# Generated by Django 5.2.17 on 2026-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0009_alter_historicalipdadmission_doctor_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalipdadmission',
            name='category',
            field=models.CharField(db_index=True, default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalipdadmission',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalipdadmission',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalipdadmission',
            name='referral',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalipdadmission',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged')], db_index=True, default='Admitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalipdpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='category',
            field=models.CharField(db_index=True, default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='referral',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ipdadmission',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged')], db_index=True, default='Admitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipdpayment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
