# Generated by Django 6.0.2 on 2026-06-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('drug', models.CharField(blank=True, max_length=200)),
                ('unit_type', models.CharField(default='TAB', max_length=20)),
                ('buffer', models.PositiveIntegerField(default=20)),
                ('hsn', models.CharField(blank=True, max_length=100)),
                ('schedule', models.CharField(default='--NA--', max_length=50)),
                ('packing', models.PositiveIntegerField(default=1)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_on_sale', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='pharmacy.pharmacyitem')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_ref', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(default='Cash', max_length=20)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pharmacy.pharmacyitem')),
            ],
        ),
    ]
