# Generated by Django 6.0.2 on 2026-06-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True)),
                ('medicines', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opd_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='opd.opdvisit')),
            ],
        ),
    ]
