# Generated by Django 5.2.17 on 2026-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_historicalprescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprescriptionmedicine',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('low_stock', 'Low Stock — Reorder Required')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicine',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('low_stock', 'Low Stock — Reorder Required')], db_index=True, default='pending', max_length=20),
        ),
    ]
