# Generated by Django 5.2.16 on 2026-07-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_historicaldoctor_historicaltestinterpretation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
