# Generated by Django 5.2.16 on 2026-07-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_alter_doctor_name_alter_historicaldoctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='historicaldoctor',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
