# Generated by Django 5.2.16 on 2026-07-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_doctor_address_historicaldoctor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='historicaldoctor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
