# Generated by Django 5.2.16 on 2026-07-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0006_sync_doctor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
