# Generated by Django 4.2.23 on 2026-06-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_ultrasoundinvestigation_ultrasoundtestmaster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalultrasoundinvestigation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalultrasoundinvestigation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='historicalultrasoundinvestigationitem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalultrasoundinvestigationitem',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='historicalultrasoundinvestigationitem',
            name='test',
        ),
        migrations.RemoveField(
            model_name='historicalultrasoundtestmaster',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='ultrasounddocument',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='ultrasoundinvestigation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='ultrasoundinvestigationitem',
            name='investigation',
        ),
        migrations.RemoveField(
            model_name='ultrasoundinvestigationitem',
            name='test',
        ),
        migrations.DeleteModel(
            name='HistoricalUltrasoundDocument',
        ),
        migrations.DeleteModel(
            name='HistoricalUltrasoundInvestigation',
        ),
        migrations.DeleteModel(
            name='HistoricalUltrasoundInvestigationItem',
        ),
        migrations.DeleteModel(
            name='HistoricalUltrasoundTestMaster',
        ),
        migrations.DeleteModel(
            name='UltrasoundDocument',
        ),
        migrations.DeleteModel(
            name='UltrasoundInvestigation',
        ),
        migrations.DeleteModel(
            name='UltrasoundInvestigationItem',
        ),
        migrations.DeleteModel(
            name='UltrasoundTestMaster',
        ),
    ]
