# Generated by Django 4.2.23 on 2026-06-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_remove_historicalultrasoundinvestigation_history_user_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='labinvestigationitem',
            constraint=models.UniqueConstraint(fields=('investigation', 'test'), name='uniq_lab_item_per_test_per_bill'),
        ),
    ]
