# Generated by Django 4.2.23 on 2026-06-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_labinvestigationitem_uniq_lab_item_per_test_per_bill'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='labinvestigationitem',
            name='uniq_lab_item_per_test_per_bill',
        ),
    ]
