# Generated by Django 5.2.17 on 2026-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_alter_labinvestigationitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallabinvestigation',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicallabinvestigation',
            name='referred_by',
            field=models.CharField(db_index=True, default='SELF', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicallabinvestigation',
            name='test_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='labinvestigation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='labinvestigation',
            name='referred_by',
            field=models.CharField(db_index=True, default='SELF', max_length=200),
        ),
        migrations.AlterField(
            model_name='labinvestigation',
            name='test_date',
            field=models.DateField(db_index=True),
        ),
    ]
