# Generated by Django 5.2.15 on 2026-06-17 19:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
        ('ipd', '0001_initial'),
        ('uhid', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(db_index=True, help_text='Patient UHID this entry belongs to. Kept as a plain field (not just a FK) so the ledger survives even if a patient record is archived or merged.', max_length=20)),
                ('tx_type', models.CharField(choices=[('OPD_BILL', 'OPD Consultation Charge'), ('IPD_BILL', 'IPD Charge'), ('LAB_BILL', 'Lab Investigation Charge'), ('PHARMACY_BILL', 'Pharmacy Sale'), ('PATIENT_PAYMENT', 'Payment Received from Patient'), ('INSURANCE_CLAIM', 'Insurance Claim Raised'), ('INSURANCE_PAYMENT', 'Payment Received from Insurer (TPA)'), ('INSURANCE_DISCOUNT', 'Insurance Rejection Written Off'), ('PATIENT_LIABILITY_SHIFT', 'Rejected Amount Shifted to Patient'), ('REFUND', 'Refund Issued'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=30)),
                ('payer_type', models.CharField(choices=[('PATIENT', 'Patient'), ('INSURANCE', 'Insurance / TPA')], default='PATIENT', help_text='Who is liable for / who paid this specific row. This is what makes split-liability (co-pay vs claim) work: two rows under the same UHID can carry different payer_type values.', max_length=20)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount charged / owed (increases the outstanding balance).', max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received / waived (decreases the outstanding balance).', max_digits=12)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('source_app', models.CharField(choices=[('opd', 'OPD'), ('ipd', 'IPD'), ('lab', 'Lab'), ('pharmacy', 'Pharmacy'), ('manual', 'Manual / Accounts Desk')], default='manual', max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='Primary key / bill number of the originating record (e.g. IPD admission id, OPD visit no, Lab bill no).', max_length=50)),
                ('tpa_name', models.CharField(blank=True, max_length=200)),
                ('insurance_company', models.CharField(blank=True, max_length=200)),
                ('policy_no', models.CharField(blank=True, max_length=100)),
                ('claim_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('claim_status', models.CharField(choices=[('NA', 'Not Applicable'), ('PENDING', 'Claim Pending'), ('PARTIAL', 'Partially Settled'), ('SETTLED', 'Fully Settled'), ('REJECTED', 'Rejected')], default='NA', max_length=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Cheque', 'Cheque'), ('NEFT/RTGS', 'NEFT/RTGS'), ('NA', 'NA')], default='NA', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('ipd_admission', models.ForeignKey(blank=True, help_text='Set when this entry is tied to a specific IPD stay (most insurance claims originate here).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ipd.ipdadmission')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='uhid.patient')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uhid', 'payer_type'], name='income_ledg_uhid_30e9a1_idx'), models.Index(fields=['claim_no'], name='income_ledg_claim_n_e4aba6_idx'), models.Index(fields=['claim_status'], name='income_ledg_claim_s_adc2a8_idx')],
            },
        ),
    ]
