# Generated by Django 5.2.15 on 2026-06-17 19:37

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_ledgerentry'),
        ('ipd', '0002_historicalipdadmission_historicalipdpayment'),
        ('uhid', '0002_historicalpatient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIncomeEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Investigation', 'Investigation'), ('OPD', 'OPD'), ('IPD', 'IPD'), ('Pharmacy', 'Pharmacy')], max_length=50)),
                ('patient_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Cheque', 'Cheque')], default='Cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical income entry',
                'verbose_name_plural': 'historical income entrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLedgerEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uhid', models.CharField(db_index=True, help_text='Patient UHID this entry belongs to. Kept as a plain field (not just a FK) so the ledger survives even if a patient record is archived or merged.', max_length=20)),
                ('tx_type', models.CharField(choices=[('OPD_BILL', 'OPD Consultation Charge'), ('IPD_BILL', 'IPD Charge'), ('LAB_BILL', 'Lab Investigation Charge'), ('PHARMACY_BILL', 'Pharmacy Sale'), ('PATIENT_PAYMENT', 'Payment Received from Patient'), ('INSURANCE_CLAIM', 'Insurance Claim Raised'), ('INSURANCE_PAYMENT', 'Payment Received from Insurer (TPA)'), ('INSURANCE_DISCOUNT', 'Insurance Rejection Written Off'), ('PATIENT_LIABILITY_SHIFT', 'Rejected Amount Shifted to Patient'), ('REFUND', 'Refund Issued'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=30)),
                ('payer_type', models.CharField(choices=[('PATIENT', 'Patient'), ('INSURANCE', 'Insurance / TPA')], default='PATIENT', help_text='Who is liable for / who paid this specific row. This is what makes split-liability (co-pay vs claim) work: two rows under the same UHID can carry different payer_type values.', max_length=20)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount charged / owed (increases the outstanding balance).', max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received / waived (decreases the outstanding balance).', max_digits=12)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('source_app', models.CharField(choices=[('opd', 'OPD'), ('ipd', 'IPD'), ('lab', 'Lab'), ('pharmacy', 'Pharmacy'), ('manual', 'Manual / Accounts Desk')], default='manual', max_length=20)),
                ('source_id', models.CharField(blank=True, help_text='Primary key / bill number of the originating record (e.g. IPD admission id, OPD visit no, Lab bill no).', max_length=50)),
                ('tpa_name', models.CharField(blank=True, max_length=200)),
                ('insurance_company', models.CharField(blank=True, max_length=200)),
                ('policy_no', models.CharField(blank=True, max_length=100)),
                ('claim_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('claim_status', models.CharField(choices=[('NA', 'Not Applicable'), ('PENDING', 'Claim Pending'), ('PARTIAL', 'Partially Settled'), ('SETTLED', 'Fully Settled'), ('REJECTED', 'Rejected')], default='NA', max_length=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Cheque', 'Cheque'), ('NEFT/RTGS', 'NEFT/RTGS'), ('NA', 'NA')], default='NA', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ipd_admission', models.ForeignKey(blank=True, db_constraint=False, help_text='Set when this entry is tied to a specific IPD stay (most insurance claims originate here).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ipd.ipdadmission')),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uhid.patient')),
            ],
            options={
                'verbose_name': 'historical Ledger Entry',
                'verbose_name_plural': 'historical Ledger Entries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
