# Generated by Django 5.2.16 on 2026-07-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_historicalincomeentry_historicalledgerentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincomeentry',
            name='category',
            field=models.CharField(choices=[('Investigation', 'Investigation'), ('OPD', 'OPD'), ('IPD', 'IPD'), ('Pharmacy', 'Pharmacy'), ('Ultrasound', 'Ultrasound'), ('OT', 'OT'), ('Extra', 'Extra / Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incomeentry',
            name='category',
            field=models.CharField(choices=[('Investigation', 'Investigation'), ('OPD', 'OPD'), ('IPD', 'IPD'), ('Pharmacy', 'Pharmacy'), ('Ultrasound', 'Ultrasound'), ('OT', 'OT'), ('Extra', 'Extra / Miscellaneous')], max_length=50),
        ),
    ]
