# Generated by Django 5.2.16 on 2026-07-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_historicalincomeentry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincomeentry',
            name='source_app',
            field=models.CharField(blank=True, default='', help_text='Module that created this entry (opd, ipd, lab, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalincomeentry',
            name='source_id',
            field=models.CharField(blank=True, default='', help_text='Bill/visit number of the originating record.', max_length=50),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='source_app',
            field=models.CharField(blank=True, default='', help_text='Module that created this entry (opd, ipd, lab, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='incomeentry',
            name='source_id',
            field=models.CharField(blank=True, default='', help_text='Bill/visit number of the originating record.', max_length=50),
        ),
    ]
