# Generated by Django 5.2.16 on 2026-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_historicalincomeentry_source_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalledgerentry',
            name='source_app',
            field=models.CharField(choices=[('opd', 'OPD'), ('ipd', 'IPD'), ('lab', 'Lab'), ('pharmacy', 'Pharmacy'), ('ultrasound', 'Ultrasound'), ('manual', 'Manual / Accounts Desk')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='source_app',
            field=models.CharField(choices=[('opd', 'OPD'), ('ipd', 'IPD'), ('lab', 'Lab'), ('pharmacy', 'Pharmacy'), ('ultrasound', 'Ultrasound'), ('manual', 'Manual / Accounts Desk')], default='manual', max_length=20),
        ),
    ]
