# Generated by Django 5.2.17 on 2026-08-09 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_sync_ledger_source_app'),
        ('ipd', '0010_perf_add_db_indexes'),
        ('uhid', '0002_historicalpatient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincomeentry',
            name='category',
            field=models.CharField(choices=[('Investigation', 'Investigation'), ('OPD', 'OPD'), ('IPD', 'IPD'), ('Pharmacy', 'Pharmacy'), ('Ultrasound', 'Ultrasound'), ('OT', 'OT'), ('Extra', 'Extra / Miscellaneous')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalincomeentry',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalincomeentry',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='incomeentry',
            name='category',
            field=models.CharField(choices=[('Investigation', 'Investigation'), ('OPD', 'OPD'), ('IPD', 'IPD'), ('Pharmacy', 'Pharmacy'), ('Ultrasound', 'Ultrasound'), ('OT', 'OT'), ('Extra', 'Extra / Miscellaneous')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='incomeentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='incomeentry',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['source_app', 'source_id'], name='ledger_source_idx'),
        ),
    ]
