# Generated by Django 6.0.2 on 2026-06-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uhid', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(default='Mr', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('guardian', models.CharField(blank=True, max_length=200)),
                ('guardian_relation', models.CharField(default='S/o', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age_years', models.PositiveIntegerField(default=0)),
                ('age_months', models.PositiveIntegerField(default=0)),
                ('age_days', models.PositiveIntegerField(default=0)),
                ('mobile', models.CharField(max_length=15)),
                ('blood_group', models.CharField(default='NA', max_length=5)),
                ('resident', models.CharField(default='India', max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
