# Generated by Django 6.0.2 on 2026-06-11 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uhid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opd_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('referral', models.CharField(blank=True, max_length=200)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('head', models.CharField(default='Opd Consultation', max_length=200)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Cheque', 'Cheque')], default='Cash', max_length=20)),
                ('reference_info', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opd_visits', to='uhid.patient')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
