# Generated by Django 5.2.15 on 2026-06-17 19:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
        ('uhid', '0002_historicalpatient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOPDVisit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('opd_no', models.CharField(db_index=True, editable=False, max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('referral', models.CharField(blank=True, max_length=200)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('head', models.CharField(default='Opd Consultation', max_length=200)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Card', 'Card'), ('Cheque', 'Cheque')], default='Cash', max_length=20)),
                ('reference_info', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uhid.patient')),
            ],
            options={
                'verbose_name': 'historical opd visit',
                'verbose_name_plural': 'historical opd visits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
