# Generated by Django 5.2.15 on 2026-06-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_historicalopdvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalopdvisit',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID used for payment (for UPI mode).', max_length=200),
        ),
        migrations.AddField(
            model_name='opdvisit',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID used for payment (for UPI mode).', max_length=200),
        ),
    ]
