# Generated by Django 5.2.15 on 2026-06-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_historicalopdvisit_upi_id_opdvisit_upi_id'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDVisitTestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opd_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='opd.opdvisit')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.labtestmaster')),
            ],
            options={
                'unique_together': {('opd_visit', 'test')},
            },
        ),
    ]

