# Generated by Django 5.2.15 on 2026-07-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_historicalopdvisittestitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalopdvisittestitem',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalopdvisittestitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
