# Generated by Django 5.2.17 on 2026-08-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0007_opdvisit_chronic_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalopdvisit',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalopdvisit',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalopdvisit',
            name='referral',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='opdvisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='opdvisit',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='opdvisit',
            name='referral',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
